import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  someSidebar: {},
  docsSidebar: [
    {
      type: "doc",
      id: "introduction",
    },
    {
      type: "category",
      label: "Getting Started",
      items: [
        {
          type: "autogenerated",
          dirName: "setup",
        },
      ],
    },
    {
      type: "category",
      label: "Configuration",
      items: [
        {
          type: "autogenerated",
          dirName: "configuration",
        },
      ],
    },
    {
      type: "category",
      label: "API Documentation",
      link: {
        type: "doc",
        id: "api/api",
      },
      items: [...require("./docs/api/endpoints/sidebar.ts")],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "guides",
        },
      ],
    },
    {
      type: "category",
      label: "Troubleshooting",
      items: [
        {
          type: "autogenerated",
          dirName: "troubleshooting",
        },
      ],
    },
    {
      type: "category",
      label: "Client Examples",
      link: {
        type: "generated-index",
        title: "Client Examples",
        description:
          "Examples of how to setup Pocket ID with different clients",
        slug: "client-examples",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "client-examples",
        },
      ],
    },
    {
      type: "link",
      label: "Contributing",
      href: "https://github.com/pocket-id/pocket-id/blob/main/CONTRIBUTING.md",
    },
    {
      type: "link",
      label: "Demo",
      href: "https://demo.pocket-id.org",
    },
  ],
};

export default sidebars;
