import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  someSidebar: {},
  docsSidebar: [
    {
      type: "doc",
      id: "introduction",
    },
    {
      type: "category",
      label: "Getting Started",
      items: [
        {
          type: "autogenerated",
          dirName: "setup",
        },
        {
          type: 'category',
          collapsible: true,
          label: 'Advanced Topics',
          link: {
            type: "generated-index",
            title: "Advanced Topics",
            description:
              "Explore advanced configuration topics for Pocket ID",
            slug: "advanced",
          },
          items: [ 
            {
              type: "autogenerated",
              dirName: "advanced",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Configuration",
      items: [
        {
          type: "autogenerated",
          dirName: "configuration",
        },
      ],
    },
    {
      type: "category",
      label: "API Documentation",
      link: {
        type: "generated-index",
        title: "API Documentation",
        description: "Explore the Pocket ID API endpoints and functionality",
        slug: "api-documentation",
      },
      items:
        process.env.API_DOCS_DISABLED === "true"
          ? []
          : [...require("./docs/api/endpoints/sidebar.ts")],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "guides",
        },
      ],
    },
    {
      type: "category",
      label: "Troubleshooting",
      items: [
        {
          type: "autogenerated",
          dirName: "troubleshooting",
        },
      ],
    },
    {
      type: "category",
      label: "Client Examples",
      link: {
        type: "generated-index",
        title: "Client Examples",
        description:
          "Examples of how to setup Pocket ID with different clients",
        slug: "client-examples",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "client-examples",
        },
      ],
    },
    {
      type: "category",
      label: "Helping Out",
      items: [
        {
          type: "autogenerated",
          dirName: "helping-out",
        },
      ],
    },
    {
      type: "link",
      label: "Demo",
      href: "https://demo.pocket-id.org",
    },
    {
      type: "link",
      label: "Discord",
      href: "https://discord.gg/Pwctrasts5",
    },
  ],
};

export default sidebars;
