name: Deploy Production Website

concurrency:
  group: deploy-prod-website
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'docs/**'
      - 'static/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'svelte.config.js'
      - '.github/workflows/deploy-production.yml'
      - 'scripts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      actions: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout pocket-id repo
        uses: actions/checkout@v5
        with:
          repository: pocket-id/pocket-id
          path: pocket-id
          ref: main

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate swagger.yaml
        run: |
          cd pocket-id/backend
          swag init -d ./internal,./internal/dto -g ../cmd/main.go -ot yaml -o ../../static -md ../../static

      - name: Add API doc tags
        run: |
          chmod +x ./scripts/add-api-doc-tags.sh
          ./scripts/add-api-doc-tags.sh

      - name: Remove pocket-id repo
        run: rm -rf pocket-id

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build website
        run: pnpm build

      - name: Deploy to Cloudflare Pages
        uses: AdrianGonz97/refined-cf-pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_NEW }}
          accountId: ${{ secrets.CF_ACCOUNT_ID_NEW }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: pocket-id-website
          deploymentName: Production
          branch: main
          directory: build
          wranglerVersion: '3'
