name: Svelte Check

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'static/**'
      - '.github/svelte-check-matcher.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'
      - 'svelte.config.js'
  pull_request:
    branches: [main, preview]
    paths:
      - 'src/**'
      - 'static/**'
      - '.github/svelte-check-matcher.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'
      - 'svelte.config.js'
  workflow_dispatch:

jobs:
  type-check:
    name: Run Svelte Check
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (optional)
        run: pnpm build

      - name: Add svelte-check problem matcher
        run: echo "::add-matcher::.github/svelte-check-matcher.json"

      - name: Run svelte-check
        run: pnpm check
