name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Checkout pocket-id repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: pocket-id/pocket-id
          path: pocket-id
          ref: main

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: pocket-id/backend/go.mod

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate swagger docs
        run: |
          cd pocket-id/backend
            # yaml + json output (json optional if you still need it)
          swag init -d ./internal,./internal/dto -g ../cmd/main.go -ot yaml,json -o ../../static -md ../../static

      - name: Add API doc tags
        run: |
          chmod +x ./scripts/add-api-doc-tags.sh
          ./scripts/add-api-doc-tags.sh

      - name: Remove pocket-id repo
        run: rm -rf pocket-id

      - name: Setup Node.js and pnpm
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true
          install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build website
        run: pnpm build
